# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a9633bc1ba1c93493e2d0dd0d3e7535c256a1e36bef9cbd2f267908f7a85e6a53ea2468ebc7d29fa4aedddf6c130245da820f439f50b633c1cf9e7dd3e4366c

test:
  secret_key_base: f9830d82dd6033c89ba18fd9ca2edd6e217e7f97f9c0e2b51348e759dfe467dee2109f7c60c996cb97dc6c86b0742ff1120d5f88ae1fcd6d6f8f45f8cf8ae67d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
